#!/bin/sh -xe

repository=${SOURCE:-"https://github.com/Himalaya-Library/Himalaya"}
this_dir="$(realpath $(dirname $0))"
source_dir="${this_dir}/Himalaya"
build_dir="${source_dir}/build"
install_dir="${build_dir}/local"
cmake_dir="${source_dir}/cmake"

clean_up() {
    rm -rf "${source_dir}"
    rm -rf build
}

trap clean_up 0
trap "exit 1" INT QUIT TERM

clean_up

git clone "${repository}" "${source_dir}"

( cd "${source_dir}" && \
  mkdir build && \
  cd build && \
  cmake -DCMAKE_INSTALL_PREFIX="${install_dir}" .. && \
  make -j4 && \
  make install )

( mkdir build && \
  cd build && \
  cmake -DCMAKE_MODULE_PATH="${cmake_dir}" -DHimalaya_INCLUDE_DIRS="${install_dir}/include" -DHimalaya_LIBRARY="${install_dir}/lib" .. && \
  cmake --build . && \
  ./example )
